In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [35]:
def decomposeLDLt(A):
    troca = False
    linha = np.zeros((1,len(A)))
    linha_tr = np.zeros((1,len(A)))

    P = np.zeros((len(A), len(A)))
    np.fill_diagonal(P, 1)

    #--------------------------------------------------------------------------------------------------
    #-----------------------------------Condensação pivotal--------------------------------------------
    #--------------------------------------------------------------------------------------------------
    
    for i in range (len(A)):

        atual = abs(A[i][i])

        for j in range (len(A)-i):

            if(abs(A[len(A)-j-1][i]) > atual):
                atual = abs(A[len(A)-j-1][i])
                num_linha = len(A)-j-1
                for k in range (len(A)):
                    linha[0][k] = A[len(A)-j-1][k]
                troca = True

        if (troca == True):

            for k in range (len(A)):
                linha_tr[0][k] = A[i][k]
            for k in range (len(A)):
                A[num_linha][k] = linha_tr[0][k]
                A[i][k] = linha[0][k]
            P[[i,num_linha]] = P[[num_linha, i]]
        troca = False

    #--------------------------------------------------------------------------------------------------
    #-----------------------------------Calculo de L e U-----------------------------------------------
    #--------------------------------------------------------------------------------------------------

    L = np.zeros((len(A), len(A)))
    np.fill_diagonal(L, 1)
    D = np.zeros((len(A), len(A)))
    U = np.zeros((len(A), len(A)))

    for i in range (len(A)-1):
        for k in range (i + 1, len(A)):
            L[k][i] = A[k][i]

    for i in range (len(A)):
        for k in range (1+i):
            if k == i:
                U[k][i] = 1
            else:
                U[k][i] = A[k][i]/A[k][k]
    for i in range(len(A)):
        D[i][i] = A[i][i]
        
    return L, D, U

In [36]:
A = np.array([[5, 3, 6, 6],
              [3, 6, 3, 3],
              [6, 3, 2, 2],
              [6, 3, 2, 9]])
decomposeLDLt(A)

(array([[1., 0., 0., 0.],
        [3., 1., 0., 0.],
        [5., 3., 1., 0.],
        [6., 3., 2., 1.]]),
 array([[6., 0., 0., 0.],
        [0., 6., 0., 0.],
        [0., 0., 6., 0.],
        [0., 0., 0., 2.]]),
 array([[1.        , 0.5       , 0.33333333, 1.5       ],
        [0.        , 1.        , 0.5       , 0.5       ],
        [0.        , 0.        , 1.        , 1.        ],
        [0.        , 0.        , 0.        , 1.        ]]))

In [37]:
L, D, Lt = decomposeLDLt(A)

In [38]:
L

array([[1., 0., 0., 0.],
       [3., 1., 0., 0.],
       [5., 3., 1., 0.],
       [6., 3., 2., 1.]])

In [39]:
Lt

array([[1.        , 0.5       , 0.33333333, 1.5       ],
       [0.        , 1.        , 0.5       , 0.5       ],
       [0.        , 0.        , 1.        , 1.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [102]:
import time

def burdens(A):
    L = np.diag(np.ones(len(A)))
    D = np.diag(np.ones(len(A)))
    v = np.ones(len(A))
    for i in range(len(A)):
        for j in range(i):
            print("v[{}] = L[{}][{}] * D[{}]".format(j, i, j, j, L[i][j],D[j][j]))
            print("v[{}] = {} * {}".format(j, L[i][j],D[j][j]))
            time.sleep(1)
            v[j] = L[i][j]*D[j][j]
        summ = 0
        for k in range(i):
            summ += L[i][k]*v[k]
        D[i][i] = A[i][i] - summ
        
        
        for j in range(i+1, len(A)):
            summ = 0
            for k in range(i):
                summ += L[j][k]*v[k]
            L[j][i] = (A[j][i] - summ)/D[i][i]
    return L, D

In [103]:
A = np.array([[5, 4, 3, 2],
              [4, 6, 3, 1],
              [3, 3, 2, 0],
              [2, 1, 0, 9]])
L, D = burdens(A)

v[0] = L[1][0] * D[0]
v[0] = 0.8 * 5.0
v[0] = L[2][0] * D[0]
v[0] = 0.6 * 5.0
v[1] = L[2][1] * D[1]
v[1] = 0.21428571428571433 * 2.8
v[0] = L[3][0] * D[0]
v[0] = 0.4 * 5.0
v[1] = L[3][1] * D[1]
v[1] = -0.21428571428571433 * 2.8
v[2] = L[3][2] * D[2]
v[2] = -14.999999999999963 * 0.07142857142857162


In [112]:
L.dot(D.dot(L.T)) - A

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  7.09974815e-30,
         3.55271368e-15]])