In [71]:
import numpy as np
import matplotlib.pyplot as plt

In [118]:
'''
Resolução de um sistema Ax = b, onde A pode ser:
- "lower": triangular inferior
- "upper": triangular superior
- "diagonal": diagonal
'''
def solve(A, b, m_type):
    if A.shape[0] != A.shape[1]:
        print("Erro, matriz nao quadrada!")
        return -1
    solution = np.zeros((A.shape[0]))
    if m_type == "lower":
        solution[0] = b[0]/A[0][0]
        print("solution[{}] = {}".format(0, solution[0]))
        for i in range(1, A.shape[0]):
            summ = 0
            for j in range(1, i + 1):
                summ += A[i][i-j]*solution[i-j]
            solution[i] = (b[i] - summ)
            print("solution[{}] = {}".format(i, solution[i]))
        return solution

    elif m_type == "upper":
        solution[A.shape[0] - 1] = b[A.shape[0]-1]/A[A.shape[0] - 1][A.shape[0] - 1]
        print("solution[{}] = {}".format(A.shape[0]-1, solution[A.shape[0]-1]))
        for i in range(2, A.shape[0]+1):
            j = A.shape[0] - i
            summ = 0
            for k in range(1, i):
                summ += A[j][j+k]*solution[j+k]
            solution[j] = (b[j] - summ)
            print("solution[{}] = {}".format(j, solution[j]))
        return solution

    elif m_type == "diagonal":
        print("solution[{}] = {}".format(0, solution[0]))
        for i in range(A.shape[0]):
            solution[i] = b[i]/A[i][i]
            print("solution[{}] = {}".format(i, solution[i]))
        return solution

'''
Decomposição LDLt de uma matriz A genérica
'''

def decomposeLDLt(A):
    L = np.diag(np.ones(len(A)))
    D = np.diag(np.ones(len(A)))
    v = np.ones(len(A))
    for i in range(len(A)):
        for j in range(i):
            v[j] = L[i][j]*D[j][j]
        summ = 0
        for k in range(i):
            summ += L[i][k]*v[k]
        D[i][i] = A[i][i] - summ
        
        
        for j in range(i+1, len(A)):
            summ = 0
            for k in range(i):
                summ += L[j][k]*v[k]
            L[j][i] = (A[j][i] - summ)/D[i][i]
    return L, D

In [119]:
A = np.array([[5, 3, 6, 6],
              [3, 6, 3, 3],
              [6, 3, 2, 2],
              [6, 3, 2, 9]])
decomposeLDLt(A)

(array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.6       ,  1.        ,  0.        ,  0.        ],
        [ 1.2       , -0.14285714,  1.        ,  0.        ],
        [ 1.2       , -0.14285714,  1.        ,  1.        ]]),
 array([[ 5.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  4.2       ,  0.        ,  0.        ],
        [ 0.        ,  0.        , -5.28571429,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  7.        ]]))

In [120]:
b = np.array([[1],
              [2],
              [3],
              [4]])

In [121]:
L, D = decomposeLDLt(A)

$LDL^T = b => DL^T = L^{-1}b$

In [122]:
print(L)
print(b)
y = solve(L, b, "lower")

[[ 1.          0.          0.          0.        ]
 [ 0.6         1.          0.          0.        ]
 [ 1.2        -0.14285714  1.          0.        ]
 [ 1.2        -0.14285714  1.          1.        ]]
[[1]
 [2]
 [3]
 [4]]
solution[0] = 1.0
solution[1] = 1.4
solution[2] = 2.0
solution[3] = 1.0


In [123]:
z = solve(D, y, "diagonal")

solution[0] = 0.0
solution[0] = 0.2
solution[1] = 0.3333333333333333
solution[2] = -0.37837837837837845
solution[3] = 0.14285714285714285


In [124]:
print(L.T)
print(z)
a = solve(L.T, z, "upper")

[[ 1.          0.6         1.2         1.2       ]
 [ 0.          1.         -0.14285714 -0.14285714]
 [ 0.          0.          1.          1.        ]
 [ 0.          0.          0.          1.        ]]
[ 0.2         0.33333333 -0.37837838  0.14285714]
solution[3] = 0.14285714285714285
solution[2] = -0.5212355212355213
solution[1] = 0.2792792792792793
solution[0] = 0.48648648648648657


In [125]:
y = solve(L, b, "lower")
z = solve(D, y, "diagonal")
a = solve(L.T, z, "upper")

solution[0] = 1.0
solution[1] = 1.4
solution[2] = 2.0
solution[3] = 1.0
solution[0] = 0.0
solution[0] = 0.2
solution[1] = 0.3333333333333333
solution[2] = -0.37837837837837845
solution[3] = 0.14285714285714285
solution[3] = 0.14285714285714285
solution[2] = -0.5212355212355213
solution[1] = 0.2792792792792793
solution[0] = 0.48648648648648657


In [126]:
print(a)

[ 0.48648649  0.27927928 -0.52123552  0.14285714]


In [127]:
a = np.linalg.inv(A).dot(b)
print(a)

[[ 0.48648649]
 [ 0.27927928]
 [-0.52123552]
 [ 0.14285714]]


In [68]:
L.dot(D.dot(L.T))

array([[5., 3., 6., 6.],
       [3., 6., 3., 3.],
       [6., 3., 2., 2.],
       [6., 3., 2., 9.]])

In [102]:
import time

def burdens(A):
    L = np.diag(np.ones(len(A)))
    D = np.diag(np.ones(len(A)))
    v = np.ones(len(A))
    for i in range(len(A)):
        for j in range(i):
            print("v[{}] = L[{}][{}] * D[{}]".format(j, i, j, j, L[i][j],D[j][j]))
            print("v[{}] = {} * {}".format(j, L[i][j],D[j][j]))
            time.sleep(1)
            v[j] = L[i][j]*D[j][j]
        summ = 0
        for k in range(i):
            summ += L[i][k]*v[k]
        D[i][i] = A[i][i] - summ
        
        
        for j in range(i+1, len(A)):
            summ = 0
            for k in range(i):
                summ += L[j][k]*v[k]
            L[j][i] = (A[j][i] - summ)/D[i][i]
    return L, D

In [103]:
A = np.array([[5, 4, 3, 2],
              [4, 6, 3, 1],
              [3, 3, 2, 0],
              [2, 1, 0, 9]])
L, D = burdens(A)

v[0] = L[1][0] * D[0]
v[0] = 0.8 * 5.0
v[0] = L[2][0] * D[0]
v[0] = 0.6 * 5.0
v[1] = L[2][1] * D[1]
v[1] = 0.21428571428571433 * 2.8
v[0] = L[3][0] * D[0]
v[0] = 0.4 * 5.0
v[1] = L[3][1] * D[1]
v[1] = -0.21428571428571433 * 2.8
v[2] = L[3][2] * D[2]
v[2] = -14.999999999999963 * 0.07142857142857162


In [112]:
L.dot(D.dot(L.T)) - A

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  7.09974815e-30,
         3.55271368e-15]])